<?php

/*================================================================
| Tutorial 36
|
| This tutorial shows how to read an Excel XLS file in PHP (the
| XLS file generated by Tutorial 09 as base template), modify
| some data and save it to another XLS file (Tutorial36.xls).
*===============================================================*/

header("Content-Type: text/html");

echo "Tutorial 36<br>";
echo "----------<br>";

// Create an instance of the class that reads Excel files
$workbook = new COM("EasyXLS.ExcelDocument");

// Read XLS file
echo "Reading file: C:\\Samples\\Tutorial09.xls<br>";
if ($workbook->easy_LoadXLSFile("C:\\Samples\\Tutorial09.xls"))
{
    // Get the table of data for the second worksheet
    $xlsSecondTable = $workbook->easy_getSheet("Second tab")->easy_getExcelTable();

    // Write some data to the second sheet
    $xlsSecondTable->easy_getCell_2("A1")->setValue("Data added by Tutorial36");

    for ($column=0; $column<5; $column++)
    {
        $xlsSecondTable->easy_getCell(1, $column)->setValue("Data " . ($column + 1));
    }

    // Export the new XLS file
    echo "Writing file: C:\Samples\Tutorial36.xls<br>";
    $workbook->easy_WriteXLSFile("C:\Samples\Tutorial36.xls");

    // Confirm export of Excel file
    if ($workbook->easy_getError() == "")
        echo "File successfully created.";
    else
        echo "Error encountered: " . $workbook->easy_getError();
}
else
{
    echo "Error reading file C:\Samples\Tutorial09.xls";
    echo $workbook->easy_getError();
}

// Dispose memory
$workbook->Dispose();	

?>
